#!/bin/sh

cd $HOME/Library/Application\ Support/Arc
RESOURCES_TO_DELETE=(*Cache StorableArchive*.json StorableWindows*.json StorableDownload*.json StorableLiveData*.json)
for resource in ${RESOURCES_TO_DELETE[@]}; do
  rm -rf $resource
done

cd $HOME/Library/Application\ Support/Arc/User\ Data/Default
find . ! -name '*Extensions*' -delete
