#!/bin/sh

delete_resources() {
  for resource in ${RESOURCES_TO_DELETE[@]}; do
    find . -name "$resource" -delete
  done
}

cd $HOME/Library/Application\ Support/Arc
RESOURCES_TO_DELETE=(*Cache StorableArchive*.json StorableWindows*.json StorableDownload*.json StorableLiveData*.json)
delete_resources $RESOURCES_TO_DELETE

cd $HOME/Library/Application\ Support/Arc/User\ Data/Default
RESOURCES_TO_DELETE=(*Cache* *Bookmarks* *Cookies* *History* *Visited*)
delete_resources $RESOURCES_TO_DELETE
